### ISSUE TITLE
Update should not require any fields

### ISSUE THREAD

**Issue by PezHead** [mniebling/table-tennis-api#2]
When trying to update the `avatarURL` of a player, both the `fullName` and `nickname` are required in the request even though they aren't being changed. Seems like it might be more convenient and less error prone to not require any fields, and only take in the fields that are being changed.

**Comment by mniebling** [comment]
You know, I agree with you. I started from a place thinking that POST updates should always include all fields (I think I was confused with PUT) and have slowly backed away from that towards more and more usability. Plus I discovered PATCH verb and thought that was the "blessed" way to do partial updates.

But, I did a bit of reading this morning and it looks like partial updates in POST are "good" with the various spec bodies: http://programmers.stackexchange.com/a/309937 

And this way seems drastically more friendly to clients AND it makes the db code easier so +1 from me.

**Comment by PezHead** [comment]
Oh man, I wasn't even aware of the PATCH verb. :/  Can stick with that if you want.

**Comment by mniebling** [comment]
But check this out, PATCH has totally weird semantics in my opinion: http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/

At least until the sensible RFC 7396, which is a candidate. So, none of this info makes me feel bad about POSTing partial updates  :)
