### ISSUE TITLE
Creating a singles match requires an array of five games

### ISSUE THREAD

**Issue by PezHead** [mniebling/table-tennis-api#5]
Seems like this requirement should be relaxed to allow for matches with 3 or 4 games. I get the following error when trying to post a match with only 3 games:

```
{
  "messages": [
    "Request parameter `games` must be an array of 5 games."
  ],
  "params": {},
  "path": "/v1/singles"
}
```

**Comment by mniebling** [comment]
DUH that is totally correct. Will change that to require 3, 4 or 5 games.
